---

tiflash_dir: "{{ deploy_dir }}/tiflash"
data_dir: "{{ deploy_dir }}/tiflash/data/db"
tmp_path: "{{ data_dir | split_string(',') | get_element_by_index(0) }}/tmp"
cluster_manager_path: "{{ deploy_dir }}/bin/tiflash/flash_cluster_manager"
cluster_manager_log: "{{ deploy_dir }}/log/tiflash_cluster_manager.log"
tiflash_tikv_log: "{{ deploy_dir }}/log/tiflash_tikv.log"
tiflash_errlog: "{{ deploy_dir }}/log/tiflash_error.log"
tiflash_server_log: "{{ deploy_dir }}/log/tiflash.log"
flash_proxy_config: "{{ deploy_dir }}/conf/tiflash-learner.toml"
raft_data_dir: "{{ data_dir | split_string(',') | get_element_by_index(0) }}/flash"
tiflash_conf_dir: "{{ deploy_dir }}/conf"
tiflash_log_dir: "{{ deploy_dir }}/log"
tiflash_scripts_dir: "{{ deploy_dir }}/scripts"
tcp_port: 9000
http_port: 8123
flash_service_port: 3930
flash_proxy_port: 20170
flash_proxy_status_port: 20292
metrics_port: 8234
